name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Check linting
        run: yarn lint

      - name: Build TS
        run: yarn build

      - name: Build Remix
        run: yarn build

